### ISSUE TITLE
ng generate.  nodepty.spawn is not a function

### ISSUE THREAD

**Issue by DaveSharman** [nrwl/angular-console#737]
Hello.

I've been using the angular console for a few months.  all was well.
Today i attempted to add an extension from the Angular Console Extensions -> @devoto13/augular-fonteawsome.   This failed (no, i didn't catch the error0.

Now, when ever i try to have the console generate something i get an error indicating that nodePty.spawn is not a funtion.
(for example, generate an application called test).

Have un-installed the vscode extension, cleared out the folder in c:\users\DaveS\.vscode\extensions.   Re-installed the angular console, and still get the error.

Suggestions on how to resolve?

Note:  sometimes the error is represented by:
Error when running 'ng generate'. Message: "The specified module could not be found.
 \\?\C:\Users\DaveS\\.vscode\extensions\nrwl.angular-console-8.0.5\node_modules\node-pty-prebuilt\build\Release\pty.node"

the directory structure shows the file in place:

![image](https://user-images.githubusercontent.com/4656980/60679134-d41a4680-9e43-11e9-86c3-ce686d74878a.png)'

As others have noted, i too am running vsCode 1.36.0.

**Comment by DaveSharman** [comment]
I should mention, generating applications, components, etc works fine using ng... from a terminal within vscode.

**Comment by jeroensneyers** [comment]
Got the same exception when building a project

**Comment by pnocera** [comment]
same here. I think it was since I updated VSCode to 1.36.0

**Comment by bampakoa** [comment]
The same error with `serve command`. This seems to be a regression from Angular 8.0.x
```
Angular CLI: 8.1.0
Node: 10.15.3
OS: win32 x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0
@angular-devkit/build-angular     0.801.0
@angular-devkit/build-optimizer   0.801.0
@angular-devkit/build-webpack     0.801.0
@angular-devkit/core              8.1.0
@angular-devkit/schematics        8.1.0
@angular/cdk                      8.0.2
@angular/material                 8.0.2
@ngtools/webpack                  8.1.0
@schematics/angular               8.1.0
@schematics/update                0.801.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2
```

**Comment by purplecure** [comment]
Same for me.
I've just upgraded to VSC 1.36.0 (Windows)

Angular CLI: 8.1.0
Node: 10.16.0
OS: win32 x64
Angular: 7.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        8.1.0
@angular/cdk                      7.3.7
@angular/cli                      8.1.0
@angular/flex-layout              7.0.0-beta.24
@angular/material                 7.3.7
@angular/pwa                      0.12.4
@angular/service-worker           7.2.12
@ngtools/webpack                  7.3.9
@schematics/angular               8.1.0
@schematics/update                0.801.0
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

**Comment by Teamop** [comment]
This issue is because the VS code updated from Electron 3 to 4 in 1.36.
Currently `node-pty-prebuilt(0.7.6)` [doesn't support Electron 4](https://github.com/daviwil/node-pty-prebuilt/issues/16), need new release from it.

**Comment by ChrisColeTech** [comment]
Both the standalone app, and the VS Code extension are now crashing after upgrading VSCode.

**Comment by mrmeku** [comment]
This should be fixed in vscode with our latest release yesterday. We no longer use node-pty-prebuilt within vscode and instead defer to executing processes in either powershell or wsl (windows users) or bash for osx and unix

**Comment by HackPoint** [comment]
> This should be fixed in vscode with our latest release yesterday. We no longer use node-pty-prebuilt within vscode and instead defer to executing processes in either powershell or wsl (windows users) or bash for osx and unix
`Error when running 'ng new'. Message: "The module '/private/var/folders/v1/3ts9x0rj6qx4bj1qyrt_rk6r0000gn/T/AppTranslocation/623DA7B9-2702-4564-90E7-1259BE4D6554/d/Angular Console.app/Contents/Resources/app/node_modules/node-pty-prebuilt/build/Release/pty.node' was compiled against a different Node.js version using NODE_MODULE_VERSION 57. This version of Node.js requires NODE_MODULE_VERSION 69. Please try re-compiling or re-installing the module (for instance, using `npm rebuild` or `npm install`)."`
